### ISSUE TITLE
CI Build

### ISSUE THREAD

**Issue by yannduran** [StefanKert/BuildVision#73]
Is it possible to access the CI build somewhere? If it'snot publicly available, maybe I could be a CI build tester?

**Comment by StefanKert** [comment]
Hi @yannduran,

first of all thanks for your help  and the comments!

You should be able to grab the latest CI build at https://dev.azure.com/stefankert/BuildVision/_build?definitionId=3&_a=summary

If not let me know. The latest build should be somehow stable. If you have time I would greatly appreciate feedback on the state :)!

I will also try to create the release pipe today to push it to the vs extensibility feed to give everyone an easy way to test the preview.

**Comment by yannduran** [comment]
@StefanKert 

Vielen Dank for the quick reply! 

Yes, that worked, but it's a very manual process. By '_vs extensibility feed_' do you mean Mads Kristensen's [VSIX Gallery](http://vsixgallery.com/)? Or something else? It'd be good to be able to add a new extension gallery to be able to be updated automatically as the CI build is pushed to GitHub. It's very easy to add the VS Gallery as an extension gallery, but anything that accomplishes the same thing would be great.

![image](https://user-images.githubusercontent.com/2031126/56847141-c368c400-691a-11e9-94fa-f4d77d06338c.png)

**Comment by StefanKert** [comment]
:) immer gerne!

Yep :) there had been a process of pushing this ti the VSIX Gallery but since I moved to Azure DevOps this needed to be added.

I just published the current version to VSIX. http://vsixgallery.com/extension/837c3c3b-8382-4839-9c9a-807b758a929f/

You should be able to grab it there :)

**Comment by yannduran** [comment]
Got it, thanks!

I used Mads Kristensen's [VSIX Gallery - nightly builds](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VSIXGallery-nightlybuilds) extension as an easy way of adding the gallery without having to do it manually.

**Comment by yannduran** [comment]
How often do you push to the VSIX gallery? Two weeks later and I still have the same version installed (v3.0.0.90). I was expecting to see the results of what you were working on(unless you haven't made any changes in the last two weeks, lol)

You mentioned that you had moved to Azure DevOps, what method are you using to push the vsix to the VSIX Gallery?

**Comment by StefanKert** [comment]
Hey there,

Since I have been at Build this week I didn‘t have a lot of time to work on BuildVision so there are no changes yet. I will probably push another version next friday because during the week I am usually pretty busy :).

I am currently using the scripts that are provided by Mads Kristensen. If you want to get the detailed scripts I can push them to the repo as well.

**Comment by yannduran** [comment]
Quick reply!!! :-)

When I was using Appveyor, I used Mads' method, but I never managed to make that work in VSTS (back then).

**Comment by StefanKert** [comment]
Basically I have a single step in my release pipe:

```powershell
(new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex
Vsix-PublishToGallery .\**\*.vsix
```

You can take a look at the build pipeline in the `azure-pipelines.yml`. I am building the stuff as usual and then just copy the files to the artifacts folder that is then published to the feed.

[https://github.com/StefanKert/BuildVision/blob/master/azure-pipelines.yml#L44]

If you need help setting up that stuff you can ping me on twitter as well :)

**Comment by StefanKert** [comment]
I think this issue can be closed right? If there are still problems with the CI build please reopen :)

**Comment by yannduran** [comment]
yes, thanks Stefan!
